name: Scheduled Weather Bot
   jobs:
     run-weather-bot:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout repo
           uses: actions/checkout@v3

         - name: Set up Python
           uses: actions/setup-python@v4
           with:
             python-version: '3.x'

-        - name: Install dependencies
-          run: |
-            pip install --upgrade pip
-            pip install -r requirements.txt
+        - name: Install dependencies
+          run: |
+            python -m pip install --upgrade pip
+            pip install requests python-dateutil

         - name: Run weather bot
           env:
             QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}
             LOCATION: ${{ secrets.LOCATION }}
             DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
             DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
           run: python weather_bot.py

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次，UTC 时间
  workflow_dispatch:

jobs:
  run-weather-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather bot
        env:
          QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}
          LOCATION: ${{ secrets.LOCATION }}
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        run: python weather_bot.py
